version: '3.7'
services:
  backend:
    image: backend
    build: ./backend
    restart: on-failure
    volumes:
    - .:/home/node/app
    - /home/node/app/node_modules
    ports:
    - 3333:3333
    environment:
      PORT: 3333
      HOST: 0.0.0.0
      NODE_ENV: production
      DB_CONNECTION: sqlite
      APP_KEY: ${APP_KEY}
  frontend:
    image: frontend
    build: ./frontend
    restart: on-failure
    depends_on:
      - backend
    links:
      - backend
    ports:
    - 8080:8080
    environment:
      PORT: 8080
      APP_KEY: ${APP_KEY}
