version: '3.7'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: adonis
      MYSQL_USER: adonis
      MYSQL_PASSWORD: adonis
      MYSQL_DATABASE: adonis
    ports:
      - "3306:3306"
    expose:
      - 3306
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - "3300:8080"
  backend:
    image: backend
    build: ./backend
    restart: on-failure
    ports:
      - "3333:3333"
    depends_on:
      - db
    environment:
      PORT: 3333
      HOST: 0.0.0.0
      NODE_ENV: production
      DB_CONNECTION: mysql
      DB_HOST: db
      APP_KEY: ${APP_KEY}
  frontend:
    image: frontend
    build: ./frontend
    restart: on-failure
    depends_on:
      - backend
    links:
      - backend
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      APP_KEY: ${APP_KEY}